name: Test Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "README.md"
      - "README"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "README.md"
      - "README"

jobs:
  build:
    name: Build App for Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: true

      - name: Update Go dependencies
        run: |
          go mod tidy

      - name: Run Tests
        run: |
          go test ./... -v

      - name: Build Binary
        run: |
          ./scripts/build.sh

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-build-artifacts
          path: bin/
          retention-days: 7
